### PR TITLE
Setup Travis with Docker Compose

### PR DESCRIPTION
**Pull request by kjdelisle**
connected to strongloop-internal/scrum-apex#203

Use Cloudant Local in Docker container with Travis CI.

### CODE REVIEW

**Comment by kjdelisle** [comment]
The tests are failing, but it's definitely doing its job now. The Cloudant Local instance spins up in Travis and runs all of our tests. Only one failure.

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Pull request merged**
