### PR TITLE
Fix test clean up

### PR DESCRIPTION
**Pull request by ssh24**
Fix tests to enable cleaning of existing model ddoc's.

connect to https://github.com/strongloop-internal/scrum-apex/issues/204

### CODE REVIEW

**Comment by ssh24** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
Closing this. As discussed we do not want to clean up the `ddoc`. https://github.com/strongloop/loopback-connector-cloudant/pull/131/files fixes the rest of the tests.

**Pull request closed without merging**
