### PR TITLE
Update cloudant.js

### PR DESCRIPTION
**Pull request by RossTapps**
I would like to add the ability to have the cloudant use a proxy agent.  The code i have added allows me to set a basic authenticated proxy on the http request.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@RossTapps can you add some test cases to verify your code? Thanks.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
I am sorry but unfortunately I have to close this pr due to missing test case.
I open an issue for this feature: https://github.com/strongloop/loopback-connector-cloudant/issues/88
Please feel free to reopen the pr if you have a chance to work on it again, and I will review it then.
Thanks for understanding :)

**Pull request closed without merging**
