### PR TITLE
Sort by date field did not work. Error: Unspecified or ambiguous sort…

### PR DESCRIPTION
**Pull request by htammen**
When sorting a date field I got the following error:
Unspecified or ambiguous sorttype. Try appending :number or :string to the sort field. checkdate

Solution: add :string to sort expression

After changing this one line of code it works as expected.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by tonyffrench** [comment]
ok to test

**Comment by tonyffrench** [comment]
@htammen can i ask you to accept the CLA?

**Comment by htammen** [comment]
@tonyffrench to be honest I don't know what I have to do now :-D. 
What is a CLA and where can I accept something?

**Comment by tonyffrench** [comment]
@htammen You should be able to click on the following https://cla.strongloop.com/agreements/strongloop/loopback-connector-cloudant

**Comment by htammen** [comment]
I accepted the agreement. So do with my ONE line of changed code whatever you want :-)

**Pull request merged**
