### PR TITLE
Fix for updateOrCreate (upsert) when id is supplied

### PR DESCRIPTION
**Pull request by djorg83**
### Description
Fix for upsert when supplying an id.

#### Related issues

- #110 

### Checklist

- [x ] New tests added or existing tests modified to cover all changes
- [x ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@djorg83 could you rebase the code? Thanks. And please commit your code in a new branch(djorg83/loopback-connector-cloudant#new_branch_name) instead of your master. 
There will be frequent PRs checked in cloudant connector, if you don't mind, can you give me access to your repo so I can rebase the code for you.

**Comment by djorg83** [comment]
@jannyHou ive added you. https://github.com/djorg83/loopback-connector-cloudant/invitations

**Comment by jannyHou** [comment]
@djorg83 Sorry it's not a correct way in git to create PR from your master branch :( I add a new branch in your repo "fix/upsert-error", and created a PR from it to our master: https://github.com/strongloop/loopback-connector-cloudant/pull/121
Do you mind we continue working on the that PR? I make it to know CI test results. Feel free to close it if you want to have your own one, just remember use the new branch instead of master :)

**Comment by jannyHou** [comment]
close in favor of https://github.com/strongloop/loopback-connector-cloudant/pull/129

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
hi @djorg83 there will be a breaking refactor in loopback-connector-cloudant@2.x, which is our current master branch, I created a new branch in your repo and opened another PR https://github.com/strongloop/loopback-connector-cloudant/pull/129 to check into our 1.x branch.

We have a customer also fails with this bug so we need to get it land asap, to speed the review I applied feedback(from my team) by myself, otherwise I will give you enough time to create the PR and gradually address comments, sorry for that, and feel free to close mine and create yours if you want to take over, the code is in branch#1.x-fix/upsert, and good to land now.

Thanks for your contribution and understanding :)

**Comment by djorg83** [comment]
Feel free to do whatever is needed to fix this issue.  You mentioned that one of your customers has an issue with this bug as well.  I work for one of your customers, and we have decided to create our own loopback mixin for performing an upsert.  We are now able to accept version 1.2.2 because we are overriding the upsert method on all models that utilize that method.

**Comment by jannyHou** [comment]
@djorg83 Your fix get published in the latest 1.x version 1.2.3:
https://github.com/strongloop/loopback-connector-cloudant/commits/1.x

Our team is sparing effort on refactoring this connector and plan to release a 2.0 version soon.
I am closing this PR since master branch will have another fix which contains breaking change, thank you for contribution.

**Pull request closed without merging**
