### PR TITLE
Increase test timeout

### PR DESCRIPTION
**Pull request by ssh24**

### CODE REVIEW

**Comment by ssh24** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@ssh24 I will create another PR with timestamp, see where does that super long time consuming happens.

**Comment by jannyHou** [comment]
I think we are good with the current timeout after changing to the stable server.

**Comment by jannyHou** [comment]
@ssh24 Since we get a new stable server for testing, shall we close this PR? Thanks.

**Comment by ssh24** [comment]
Yes @jannyHou Closing this since we switched to the new server.

**Pull request closed without merging**
