### PR TITLE
Fix init config

### PR DESCRIPTION
**Pull request by ssh24**
Fix init config to get latest config from loopbackrc

### CODE REVIEW

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
We need to make sure that the rc loader doesn't run if we're on Travis CI (since that will never work).

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
This PR is not needed. CIS-jenkins config has been updated to use the same ones set in loopbackrc.

**Pull request closed without merging**
