### PR TITLE
Update package.json to remove security vulnerability

### PR DESCRIPTION
**Pull request by hibaymj**
Updating debug required version from 2.2.0 to 2.6.9.
> eslint .

(+) 1 vulnerabilities found
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ debug                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ CVSS          │ 3.7 (Low)                                                       │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 2.2.0                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <= 2.6.8 || >= 3.0.0 <= 3.0.1                                   │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                    │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ RPC-Integration@1.0.0 > loopback-connector-cloudant@2.0.3 > cl… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/534                          │
└───────────────┴─────────────────────────────────────────────────────────────────┘

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by virkt25** [comment]
@hibaymj Can you please sign the CLA

**Comment by hibaymj** [comment]
Not a problem, done.

**Comment by virkt25** [comment]
@slnode ok to test

**Comment by virkt25** [comment]
@slnode please test

**Comment by virkt25** [comment]
@slnode test please

**Comment by virkt25** [comment]
@hibaymj Can you re-word the commit message to be 50 character or less so Commit Linter passes -- and then we should be good to land it and do a release.

**Comment by hibaymj** [comment]
Done and done.

**Comment by virkt25** [comment]
Thanks @hibaymj . PR Landed. Thanks for your contribution! New version with the fix is 2.0.4

**Pull request merged**
