### PR TITLE
Update juggler version to ^3.0.0-alpha.7

### PR DESCRIPTION
**Pull request by jannyHou**
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1041

### CODE REVIEW

**Comment by superkhau** [comment]
@bajtos We should merge this one in too (assuming failures are due to lack of CI), follow up issue at https://github.com/strongloop-internal/scrum-loopback/issues/1053

**Comment by bajtos** [comment]
@superkhau @jannyHou I don't have time to investigate details, I'll leave the decision up to you.

**Comment by jannyHou** [comment]
@superkhau PTAL again. Thanks :)

**Comment by jannyHou** [comment]
Green now 🎆

**Pull request merged**
